Mar 15 01:55:03 3dr_solo local1.info pix: pixhawk.py starting
Mar 15 01:55:03 3dr_solo local1.info pix: checking baud...
Mar 15 01:55:03 3dr_solo local1.info pix: found at 921600
Mar 15 01:55:03 3dr_solo local1.info pix: Status Text: STATUSTEXT {severity : 6, text : ArduCopter V4.0.1 (61f191de)}
Mar 15 01:55:03 3dr_solo local1.warn pix: firmware is not specifically for solo
Mar 15 01:55:03 3dr_solo local1.info pix: build version received in 0.010 sec
Mar 15 01:55:03 3dr_solo local1.info pix: build version build=4.0.1 ardupilot=61f191d
Mar 15 01:55:03 3dr_solo local1.info pix: {'ardupilot_git_hash': '61f191d\x00', 'build_version': '4.0.1', 'px4_git_hash': '\x00\x00\x00\x00\x00\x00\x00\x00', 'nuttx_git_hash': 'cb42c85\x00'}
Mar 15 01:55:03 3dr_solo local1.info pix: now running:
Mar 15 01:55:03 3dr_solo local1.info pix: build_version        4.0.1
Mar 15 01:55:03 3dr_solo local1.info pix: ardupilot_git_hash   61f191d
Mar 15 01:55:03 3dr_solo local1.info pix: px4_git_hash         
Mar 15 01:55:03 3dr_solo local1.info pix: nuttx_git_hash       cb42c85
Mar 15 01:55:03 3dr_solo local1.info pix: pixhawk status: ready
Mar 15 01:55:03 3dr_solo local1.info pix: Not on recovery partition
Mar 15 01:55:03 3dr_solo local1.info pix: No firmware file found
Mar 15 01:55:03 3dr_solo local1.info pix: pixhawk.py finished
Mar 15 01:55:10 3dr_solo local1.info unlock: built Jan 26 2020 18:40:01
Mar 15 01:55:10 3dr_solo local1.info unlock: rc is not locked
Mar 15 01:55:10 3dr_solo local1.info pair: pair_solo.py starting
Mar 15 01:55:10 3dr_solo local1.info pair: using default check_versions=True
Mar 15 01:55:10 3dr_solo local1.info pair: sololink version "4.0.0"
Mar 15 01:55:10 3dr_solo local1.info pair: firmware version "4.0.1"
Mar 15 01:55:10 3dr_solo local1.info pair: pairing using wlan0
Mar 15 01:55:10 3dr_solo local1.info pair: bringing up network...
Mar 15 01:55:10 3dr_solo local1.info pair: network already up
Mar 15 01:55:10 3dr_solo local1.info pair: establishing connection...
Mar 15 01:55:10 3dr_solo local1.info pair: controller version "4.0.0"; firmware "OpenSolo-4.0.0"
Mar 15 01:55:10 3dr_solo local1.info pair: switching to runlevel.READY
Mar 15 01:55:10 3dr_solo local1.info dl: dataflash_logger starting: built Jan 26 2020 18:39:35
Mar 15 01:55:10 3dr_solo local1.info dl: df-tfc: connecting to telem-forwarder at 10.1.1.10:14560
Mar 22 16:02:45 3dr_solo local1.info pair: timeout waiting for ack
Mar 22 16:03:19 3dr_solo local1.info pair: ack received after timeout
Mar 22 16:03:58 3dr_solo local1.info pair: timeout waiting for ack
Mar 22 16:04:09 3dr_solo local1.info pair: ack received after timeout
Mar 22 16:04:24 3dr_solo local1.info dl: Failed sendto: Network is unreachable
Mar 22 16:07:35 3dr_solo local1.info pair: timeout waiting for ack
Mar 22 16:07:46 3dr_solo local1.info pair: ack received after timeout
Mar 22 16:08:15 3dr_solo local1.info dl: Failed sendto: Network is unreachable
Mar 22 16:24:06 3dr_solo local1.info dl: mh-dfl: Starting log, target is (1/155), I am (57/57)
Mar 22 16:24:06 3dr_solo local1.info dl: mh-dfl: Opened log file (/log/dataflash/16.BIN)
Mar 22 16:24:06 3dr_solo local1.err dl: mh-dfl: long time between messages (-860911212)
Mar 22 16:24:07 3dr_solo local1.err dl: mh-dfl: long time between messages (259420)
Mar 22 16:24:08 3dr_solo local1.info dl: mh-dfl: Current log size: 20000
Mar 22 16:24:18 3dr_solo local1.err dl: mh-dfl: long time between messages (105919)
Mar 22 16:24:19 3dr_solo local1.info dl: mh-dfl: Current log size: 180000
Mar 22 16:24:31 3dr_solo local1.info dl: mh-dfl: No data packets received for some time (now=3459035585 last=3449028290).  Closing log.  Final log size: 220000
Mar 22 16:24:54 3dr_solo local1.info dl: mh-dfl: Starting log, target is (1/155), I am (57/57)
Mar 22 16:24:54 3dr_solo local1.info dl: mh-dfl: Opened log file (/log/dataflash/17.BIN)
Mar 22 16:24:54 3dr_solo local1.err dl: mh-dfl: long time between messages (32942248)
Mar 22 16:24:55 3dr_solo local1.info dl: mh-dfl: Current log size: 12400
Mar 22 16:25:05 3dr_solo local1.info dl: mh-dfl: Current log size: 172400
